@startuml
!include <C4/C4_Container>

Person(user, "User", "The user of the system")

System_Boundary(local, "Culturebook system") {
    ' Client
    Container(client, "Mobile App", "Android")

    ' Backend
    System(api, "API", "The Ktor API")
}

' External systems
System_Ext(google, "Google Cloud Services", "Google sign in")
System_Ext(firebase, "Firebase", "Firebase configuration and analytics")
System_Ext(rekognition, "AWS Rekognition", "Content moderation platform")

' Layout

Lay_U(client, user)
Lay_U(api, client)

' Api Relations
Rel(api, rekognition, "Media")
Rel(api, google, "JWT")
Rel(api,firebase, "Json")

' Client relations
Rel(client,firebase, "Json")
BiRel(client, api, "Uses", "Retrofit")
' User relations
BiRel(user, client, "Interacts")
Rel(user, google, "Approves")
@enduml
