@startuml
!include <C4/C4_Container>

' Style
AddRelTag("response_tag", $lineStyle = DashedLine())

Person(user, "User", "The user of the system")

System_Boundary(local, "Culturebook system") {
    ' Client

    System_Boundary(client_bound, "Mobile App") {
        System(view_layer, "View Fragments", "Kotlin, XML")
        System(view_models, "View Models", "Kotlin")
        System(data_layer, "Data Layer", "Kotlin")

        ' Layout
        Lay_L(view_layer, view_models)
        Lay_L(view_models, data_layer)


        ' Relations
        Rel_R(view_layer, view_models, "UI Events")
        Rel_R(view_models, data_layer, "Repository calls")

        Rel_L(view_models, view_layer, "UI States", $tags="response_tag")
        Rel_L(data_layer, view_models, "Kotlin Flows", $tags="response_tag")
    }

    ' Backend
    System_Boundary(api_bound, "API") {
        System(api_gw, "API Gateway", "Ktor")
        Container(auth, "Authentication Module", "Handles client and inter-process authentication ")
        Container(nearby, "Nearby Module", "Handles the nearby feature's business logic")
        Container(element, "Elements Module", "Handles the element details feature's business logic")
        Container(contribution, "Contributions Module", "Handles the contribution details feature's business logic")
        Container(add_element, "Add element Module", "Handles the add element feature's business logic")
        Container(account, "Account Module", "Handles the account feature's business logic")
        ContainerDb(db, "Data access Module", "Handles all read/write operations")
        
        ' Relations

        BiRel_D(api_gw, auth, "Uses")
        BiRel_D(api_gw, nearby, "Uses")
        BiRel_D(api_gw, element, "Uses")
        BiRel_D(api_gw, contribution, "Uses")
        BiRel_D(api_gw, add_element, "Uses")
        BiRel_D(api_gw, account, "Uses")

        BiRel_U(db, auth, "Uses", $tags="response_tag")
        BiRel_U(db, nearby, "Uses", $tags="response_tag")
        BiRel_U(db, element, "Uses", $tags="response_tag")
        BiRel_U(db, contribution, "Uses", $tags="response_tag")
        BiRel_U(db, add_element, "Uses", $tags="response_tag")
        BiRel_U(db, account, "Uses", $tags="response_tag")
    }
}

' External systems
System_Ext(external, "External Systems")

' Layout & Styles
Lay_U(client_bound, user)
Lay_U(api_gw, client_bound)

' Api Relations
Rel_D(data_layer, api_gw, "Remote API calls")
Rel_U(api_gw, data_layer, "API response", $tags="response_tag")

' User relations
BiRel(user, view_layer, "Uses")
@enduml
